[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings=[
	'@mangrovedao/semitransferable-token/=lib/mangrovedao/semitransferable-token/src/'
]
solc_version = '0.8.13'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config